<?php
return array(
		"siteUrl"=>"http://127.0.0.1/ubiquity/",
		"database"=>[
				"type"=>"mysql",
				"dbName"=>"innodb-big",
				"serverName"=>"127.0.0.1",
				"port"=>"3306",
				"user"=>"sio2a",
				"password"=>"sio2a",
				"options"=>[],
				"cache"=>false
		],
		"sessionName"=>null,
		"namespaces"=>[],
		"templateEngineOptions"=>array("cache"=>false),
		"test"=>false,
		"debug"=>false,
		"cache"=>["directory"=>"cache/","system"=>"Ubiquity\\cache\\system\\ArrayCache","params"=>[]],
		"mvcNS"=>["models"=>"models","controllers"=>"controllers","rest"=>""]
);
